from dataclasses import dataclass


@dataclass(frozen=True)
class CompanyJobSourceSeed:
    company: str
    source_url: str
    source_type: str
    url_patterns: tuple[str, ...]
    notes: str
    confidence: str = "high"


JOB_SOURCE_SEEDS: tuple[CompanyJobSourceSeed, ...] = (
    CompanyJobSourceSeed(
        "Hudson River Trading",
        "https://www.hudsonrivertrading.com/careers/",
        "official_careers",
        ("/careers/", "greenhouse.io"),
        "Official careers page; role details are surfaced from the HRT careers experience.",
    ),
    CompanyJobSourceSeed(
        "Jane Street",
        "https://www.janestreet.com/join-jane-street/open-roles/",
        "official_careers",
        ("/join-jane-street/open-roles/",),
        "Official open roles page; querystring filters are categories, not separate job details.",
    ),
    CompanyJobSourceSeed(
        "D. E. Shaw",
        "https://www.deshaw.com/careers",
        "official_careers",
        ("/careers/", "/recruit/jobs/"),
        "Official careers page; job detail URLs use /careers/<role>-<id>.",
    ),
    CompanyJobSourceSeed(
        "Two Sigma",
        "https://careers.twosigma.com/",
        "official_careers",
        ("careers.twosigma.com", "/careers/OpenRoles/"),
        "Official careers portal; reject twosigma.com /businesses/ and article pages.",
    ),
    CompanyJobSourceSeed(
        "Citadel",
        "https://www.citadel.com/careers/open-opportunities/",
        "official_careers",
        ("/careers/details/", "/careers/open-opportunities/"),
        "Official open opportunities page; job postings use /careers/details/.",
    ),
    CompanyJobSourceSeed(
        "Citadel Securities",
        "https://www.citadelsecurities.com/careers/open-opportunities/",
        "official_careers",
        ("/careers/details/", "/careers/open-opportunities/"),
        "Official open opportunities page; job postings use /careers/details/.",
    ),
    CompanyJobSourceSeed(
        "Point72",
        "https://careers.point72.com/",
        "official_careers",
        ("careers.point72.com", "CSJobDetail", "CSCareerSearch"),
        "Official careers portal; reject point72.com marketing/category links.",
    ),
    CompanyJobSourceSeed(
        "Cubist Systematic Strategies",
        "https://careers.point72.com/",
        "official_careers",
        ("careers.point72.com", "CSJobDetail", "CSCareerSearch", "focus=Systematic"),
        "Cubist roles are listed through Point72 careers.",
    ),
    CompanyJobSourceSeed(
        "Millennium Management",
        "https://www.mlp.com/careers/",
        "official_careers",
        ("mlp.eightfold.ai/careers", "pid="),
        "Official careers page links into Millennium's Eightfold job portal.",
    ),
    CompanyJobSourceSeed(
        "Squarepoint Capital",
        "https://www.squarepoint-capital.com/open-opportunities",
        "official_careers",
        ("/open-opportunities",),
        "Official open opportunities page.",
    ),
    CompanyJobSourceSeed(
        "Susquehanna International Group",
        "https://careers.sig.com/",
        "official_careers",
        ("careers.sig.com",),
        "Official SIG careers portal.",
    ),
    CompanyJobSourceSeed(
        "Optiver",
        "https://optiver.com/working-at-optiver/career-opportunities/",
        "official_careers",
        ("/working-at-optiver/career-opportunities/",),
        "Official career opportunities page; reject /career-hub/ article links.",
    ),
    CompanyJobSourceSeed(
        "DRW",
        "https://drw.com/work-at-drw/listings",
        "official_careers",
        ("/work-at-drw/listings/", "/work-at-drw/listings"),
        "Official DRW listings page.",
    ),
    CompanyJobSourceSeed(
        "Jump Trading",
        "https://www.jumptrading.com/careers/",
        "official_careers",
        ("/careers/",),
        "Official careers page; reject /trading and homepage links.",
    ),
    CompanyJobSourceSeed(
        "Tower Research Capital",
        "https://www.tower-research.com/open-positions/",
        "official_careers",
        ("/open-positions/", "tower-research.com/careers"),
        "Official open positions page.",
    ),
    CompanyJobSourceSeed(
        "Akuna Capital",
        "https://akunacapital.com/careers",
        "official_careers",
        ("/careers",),
        "Official careers page; reject /what-we-do/ links.",
    ),
    CompanyJobSourceSeed(
        "Chicago Trading Company",
        "https://www.chicagotrading.com/careers/",
        "official_careers",
        ("/posting?req=",),
        "Official CTC job postings use /posting?req=.",
    ),
    CompanyJobSourceSeed(
        "Five Rings",
        "https://fiverings.com/careers/",
        "ats_job_board",
        ("job-boards.greenhouse.io/fiveringsllc/jobs/",),
        "Official careers page links to Greenhouse job details.",
    ),
    CompanyJobSourceSeed(
        "Group One Trading",
        "https://www.group1.com/careers/",
        "ats_job_board",
        ("group1.applicantpro.com/jobs/",),
        "Official careers page links to ApplicantPro job details.",
    ),
    CompanyJobSourceSeed(
        "Renaissance Technologies",
        "https://www.rentec.com/Careers.action",
        "official_careers",
        ("Careers.action?jobs=true&selectedPosition=",),
        "Official Rentec careers page exposes selectedPosition job links.",
    ),
    CompanyJobSourceSeed(
        "WorldQuant",
        "https://www.worldquant.com/careers/",
        "official_careers",
        ("/career-listing/?id=",),
        "Official careers page; reject ideas, ventures, foundry, and university links.",
    ),
    CompanyJobSourceSeed(
        "Capula Investment Management",
        "https://www.capulaglobal.com/careers/",
        "ats_job_board",
        ("capula-investment-management-ltd.workable.com/jobs/",),
        "Official careers page links to Workable job details.",
    ),
    CompanyJobSourceSeed(
        "PanAgora Asset Management",
        "https://www.panagora.com/careers/",
        "official_careers",
        ("/careers/",),
        "Official careers page; reject /insights/ research archive links.",
    ),
    CompanyJobSourceSeed(
        "Goldman Sachs",
        "https://www.goldmansachs.com/careers/",
        "official_careers",
        ("/careers/",),
        "Official Goldman Sachs careers page; current generic crawler needs tighter role search.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "JPMorgan Chase",
        "https://careers.jpmorgan.com/us/en/home",
        "official_careers",
        ("careers.jpmorgan.com", "/jobs/"),
        "Official JPMorgan careers portal; reject jpmorgan.com insights pages.",
    ),
    CompanyJobSourceSeed(
        "Morgan Stanley",
        "https://www.morganstanley.com/careers/career-opportunities-search",
        "official_careers",
        ("/careers/career-opportunities-search",),
        "Official Morgan Stanley career opportunities search page.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Citi",
        "https://jobs.citi.com/",
        "official_careers",
        ("jobs.citi.com",),
        "Official Citi jobs portal.",
    ),
    CompanyJobSourceSeed(
        "Bank of America",
        "https://careers.bankofamerica.com/",
        "official_careers",
        ("careers.bankofamerica.com",),
        "Official Bank of America careers portal.",
    ),
    CompanyJobSourceSeed(
        "Balyasny Asset Management",
        "https://www.bamfunds.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Qube Research & Technologies",
        "https://www.qube-rt.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "IMC Trading",
        "https://www.imc.com/us/careers/jobs/",
        "official_careers",
        ("/us/careers/jobs",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "XTX Markets",
        "https://www.xtxmarkets.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Virtu Financial",
        "https://www.virtu.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Flow Traders",
        "https://www.flowtraders.com/careers/job-search/",
        "official_careers",
        ("/careers/job-search/", "/careers/"),
        "Official job-search surface linked from the careers page; /careers/jobs can return 404.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Old Mission",
        "https://www.oldmissioncapital.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Belvedere Trading",
        "https://www.belvederetrading.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Maven Securities",
        "https://www.mavensecurities.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "TransMarket Group",
        "https://www.transmarketgroup.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Quantlab",
        "https://www.quantlab.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Wolverine Trading",
        "https://www.wolve.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Headlands Technologies",
        "https://www.headlandstech.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Radix Trading",
        "https://radixtrading.co/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Mako Trading",
        "https://www.mako.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Da Vinci Derivatives",
        "https://davinciderivatives.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Eclipse Trading",
        "https://www.eclipsetrading.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Peak6",
        "https://www.peak6.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "WH Trading",
        "https://www.whtrading.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "All Options",
        "https://alloptions.nl/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "AQR Capital Management",
        "https://www.aqr.com/careers",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Man Group",
        "https://www.man.com/careers",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Winton",
        "https://www.winton.com/careers",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "G-Research",
        "https://www.gresearch.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Schonfeld",
        "https://www.schonfeld.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Verition Fund Management",
        "https://www.verition.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "ExodusPoint",
        "https://www.exoduspoint.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "PDT Partners",
        "https://www.pdtpartners.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "The Voleon Group",
        "https://www.voleon.com/careers",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Trexquant",
        "https://www.trexquant.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "AlphaGrep",
        "https://www.alpha-grep.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "CFM",
        "https://www.cfm.com/join-us/",
        "official_careers",
        ("/join-us",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Systematica Investments",
        "https://www.systematica.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Aspect Capital",
        "https://www.aspectcapital.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Graham Capital Management",
        "https://www.grahamcapital.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Brevan Howard",
        "https://www.brevanhoward.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Marshall Wace",
        "https://www.mwam.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Rokos Capital Management",
        "https://www.rokoscapital.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Tudor Investment Corporation",
        "https://www.tudor.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Aquatic Capital Management",
        "https://aquatic.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Voloridge",
        "https://www.voloridge.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Arrowstreet Capital",
        "https://www.arrowstreetcapital.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Kepos Capital",
        "https://www.keposcapital.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Walleye Capital",
        "https://www.walleyecapital.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Paloma Partners",
        "https://www.paloma.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Laurion Capital",
        "https://www.laurioncapital.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Eisler Capital",
        "https://www.eislercapital.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "LMR Partners",
        "https://www.lmrpartners.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Quadrature",
        "https://quadrature.ai/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Teza Technologies",
        "https://www.teza.com/careers/",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "BlackRock",
        "https://careers.blackrock.com/",
        "official_careers",
        ("careers.blackrock.com",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Acadian Asset Management",
        "https://www.acadian-asset.com/careers",
        "official_careers",
        ("/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
    CompanyJobSourceSeed(
        "Dimensional Fund Advisors",
        "https://www.dimensional.com/us-en/careers",
        "official_careers",
        ("/us-en/careers",),
        "Official careers source from target seed list; URL structure needs evaluator review before hard crawler validation.",
        "medium",
    ),
)
